name: Backend Docker CI 

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

# changing from code verification to docker build verification
jobs: 
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: |
          docker build -t backend-ci ./backend

      - name: Verify image exists
        run: |
          docker images | grep backend-ci
