name: Backend Docker CI 

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

# changing from code verification to docker build verification
# now changing from no tagging, to github tagging for tracability
jobs: 
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image tag via GIT SHA
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV


      - name: Build backend Docker image (SHA+Latest)
        run: |
          docker build \
          -t ${{ secrets.NAME }}/backend_databaseproject:${IMAGE_TAG} \
          -t ${{ secrets.NAME }}/backend_databaseproject:latest \
          ./backend

      - name: Verify image exists
        run: |
          docker images | grep backend
      
      - name: Push to DOCKER HUB 
        run: |
          docker push ${{ secrets.NAME }}/backend_databaseproject:${IMAGE_TAG}
          docker push ${{ secrets.NAME }}/backend_databaseproject:latest
